PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX w3c: <http://www.w3.org/2004/02/skos/core#>
PREFIX emobon: <http://www.embrc.eu/emobon/EmoBonOntology#>
SELECT DISTINCT 
    ?observations 
    ?property 
    ?observationresult 
    ?unit 
    ?unitlabel
    ?unitaltlabel
    ?resultnumeric 
    ?sample 
    ?metadatasample 
    ?propertyaltlabel 
    ?filtrationtime
    ?samplesize
    ?sampletype
    ?sampledepth

WHERE  {
	?observations a sosa:Observation .
    ?observations sosa:observedProperty ?property .
    ?property w3c:altLabel ?propertyaltlabel .
    ?observationresult <http://qudt.org/schema/qudt/unit> ?unit .
    ?unit w3c:prefLabel ?unitlabel .
    ?unit w3c:altLabel ?unitaltlabel .
    ?observationresult <http://qudt.org/schema/qudt/numericValue> ?resultnumeric .
    ?observations sosa:hasResult ?observationresult .
    ?observations sosa:hasFeatureOfInterest ?sample .
    ?sample sosa:hasResult ?metadatasample .
    ?metadatasample emobon:filtrationTime ?filtrationtime .
    ?metadatasample emobon:hasSampleSize ?samplesize .
    ?metadatasample sosa:isSampleOf ?sampletype .
    ?metadatasample emobon:sampleDepth ?sampledepth .
}